# Configuration for LLM-powered Game Player

# Model configuration
model:
  api_url: "http://localhost:8000"  # vLLM server with Qwen2.5-VL model
  summary_interval: 10              # Generate summary every X turns when summary feature is enabled
  max_tokens: 100                   # Max tokens to generate for action decision
  temperature: 0.2                  # Lower temperature for more focused responses

# Game configurations
games:
  # Example Game Boy / Game Boy Color game configuration
  pokemon_red:
    rom: "/path/to/PokemonRed.gb"   # Replace with actual path to your ROM
    emulator: "pyboy"
    actions: ["Up", "Down", "Left", "Right", "A", "B", "Start", "Select"]
    action_delay: 0.5               # Seconds to wait after each action

  # Example Game Boy Advance game configuration  
  pokemon_emerald:
    rom: "/path/to/PokemonEmerald.gba"  # Replace with actual path to your ROM
    emulator: "mgba"
    actions: ["Up", "Down", "Left", "Right", "A", "B", "L", "R", "Start", "Select"]
    action_delay: 1.0               # Seconds to wait after each action

  # Add more games as needed