# Configuration for LLM-powered Game Player

# Model configuration
model:
  # Common settings
  api_url: "http://127.0.0.1:8000"  # API server URL for both backends
  backend: "auto"                   # "auto", "vllm", or "llama.cpp"
  summary_interval: 10              # Generate summary every X turns when summary feature is enabled
  max_tokens: 200                   # Max tokens to generate for action decision (increased for JSON responses)
  temperature: 0.2                  # Lower temperature for more focused responses
  
  # Response format configuration
  json_schema_support: true         # Whether the model supports JSON schema responses
  
  # Frame caching configuration
  enable_cache: true                # Enable frame caching to reduce API calls
  cache_dir: "output/cache"         # Directory to store cached frames
  similarity_threshold: 0.95        # Threshold for considering frames similar (0-1)
  
  # llama.cpp specific settings (for Mac compatibility)
  autostart_server: false           # Whether to automatically start the model server
  model_path: "models/llava-v1.5-7b-Q4_K_S.gguf"  # Path to GGUF model file from second-state
  model_url: "https://huggingface.co/second-state/Llava-v1.5-7B-GGUF/resolve/main/llava-v1.5-7b-Q4_K_S.gguf"  # URL for auto-download
  n_gpu_layers: -1                  # Number of layers to offload to GPU (-1 for all)
  n_ctx: 2048                       # Context window size

# Logging configuration
logging:
  level: "INFO"                     # Logging level (DEBUG, INFO, WARNING, ERROR)
  save_frames: true                 # Save frames to disk for debugging
  frames_dir: "output/logs/frames"  # Directory to save frames
  log_file: "output/logs/emuvlm.log" # Log file path

# Game configurations
games:
  # Game Boy / Game Boy Color game configuration
  pokemon_blue:
    rom: "/Users/ericflo/Development/emuvlm/roms/gb/Pokemon - Blue Version (UE) [S][T+Por1.2_CBT].gb"
    emulator: "pyboy"
    actions: ["Up", "Down", "Left", "Right", "A", "B", "Start", "Select"]
    action_delay: 0.5               # Seconds to wait after each action
    # Game-specific timing configurations
    timing:
      menu_nav_delay: 0.3           # Faster delay for menu navigation
      battle_anim_delay: 1.5        # Longer delay for battle animations
      text_scroll_delay: 0.8        # Medium delay for text scrolling

  final_fantasy_legend_ii:
    rom: "/Users/ericflo/Development/emuvlm/roms/gb/Final Fantasy Legend II (U) [b2].gb"
    emulator: "pyboy"
    actions: ["Up", "Down", "Left", "Right", "A", "B", "Start", "Select"]
    action_delay: 0.5               # Seconds to wait after each action
    # Game-specific timing configurations
    timing:
      menu_nav_delay: 0.3           # Delay for menu navigation
      battle_command_delay: 0.4     # Delay between selecting battle commands
      battle_anim_delay: 1.0        # Delay for battle animations
      text_scroll_delay: 0.6        # Delay for text scrolling
      overworld_movement_delay: 0.4 # Delay for moving in the overworld

  zelda_links_awakening:
    rom: "/Users/ericflo/Development/emuvlm/roms/gb/zelda_links_awakening.gb"
    emulator: "pyboy"
    actions: ["Up", "Down", "Left", "Right", "A", "B", "Start", "Select"]
    action_delay: 0.4               # Seconds to wait after each action
    game_type: "zelda"              # Game type for specific handling
    # Game-specific timing configurations
    timing:
      menu_nav_delay: 0.3           # Delay for inventory navigation
      dialog_delay: 1.0             # Delay for NPC dialog
      screen_transition_delay: 0.7  # Delay for screen transitions
      item_use_delay: 0.5           # Delay after using items
    # Game-specific settings
    settings:
      detect_loading_screens: true  # Enable loading screen detection
      frame_analysis: true          # Enable more detailed frame analysis
      max_blank_frames: 5           # Maximum consecutive blank frames before skipping
  
  # Game Boy Advance game configuration  
  pokemon_emerald:
    rom: "/path/to/PokemonEmerald.gba"  # Replace with actual path to your ROM
    emulator: "mgba"
    actions: ["Up", "Down", "Left", "Right", "A", "B", "L", "R", "Start", "Select"]
    action_delay: 1.0               # Seconds to wait after each action
    # Game-specific timing configurations
    timing:
      menu_nav_delay: 0.5           # Delay for menu navigation
      battle_anim_delay: 2.0        # Longer delay for battle animations
      text_scroll_delay: 1.0        # Delay for text scrolling

  # Add more games as needed

# Session configuration
sessions:
  enable_save: true                 # Enable session saving/loading
  save_dir: "output/sessions"       # Directory to store session data
  auto_save_interval: 50            # Auto-save session every X turns