# Configuration for LLM-powered Game Player

# Model configuration
model:
  # Common settings
  api_url: "http://127.0.0.1:8000"  # API server URL for both backends
  backend: "auto"                   # "auto", "vllm", or "llama.cpp"
  summary_interval: 10              # Generate summary every X turns when summary feature is enabled
  max_tokens: 200                   # Max tokens to generate for action decision (increased for JSON responses)
  temperature: 0.2                  # Lower temperature for more focused responses
  
  # Response format configuration
  json_schema_support: true         # Whether the model supports JSON schema responses
  
  # Frame caching configuration
  enable_cache: true                # Enable frame caching to reduce API calls
  cache_dir: "output/cache"         # Directory to store cached frames
  similarity_threshold: 0.95        # Threshold for considering frames similar (0-1)
  
  # llama.cpp specific settings (for Mac compatibility)
  autostart_server: false           # Whether to automatically start the model server
  model_path: "models/llava-v1.5-7b-Q4_K_S.gguf"  # Path to GGUF model file from second-state
  model_url: "https://huggingface.co/second-state/Llava-v1.5-7B-GGUF/resolve/main/llava-v1.5-7b-Q4_K_S.gguf"  # URL for auto-download
  n_gpu_layers: -1                  # Number of layers to offload to GPU (-1 for all)
  n_ctx: 2048                       # Context window size

# Logging configuration
logging:
  level: "INFO"                     # Logging level (DEBUG, INFO, WARNING, ERROR)
  save_frames: true                 # Save frames to disk for debugging
  frames_dir: "output/logs/frames"  # Directory to save frames
  log_file: "output/logs/emuvlm.log" # Log file path

# Game configurations
games:
  # Game Boy / Game Boy Color game configuration - Fully Supported
  pokemon_blue:
    rom: "/Users/ericflo/Development/emuvlm/roms/gb/Pokemon - Blue Version (USA, Europe) (SGB Enhanced).zip"
    emulator: "pyboy"
    actions: ["Up", "Down", "Left", "Right", "A", "B", "Start", "Select"]
    action_delay: 0.5               # Seconds to wait after each action
    game_type: "pokemon"            # Set game type to identify it as Pokemon
    # Game-specific timing configurations
    timing:
      menu_nav_delay: 0.3           # Faster delay for menu navigation
      battle_anim_delay: 1.5        # Longer delay for battle animations
      text_scroll_delay: 0.8        # Medium delay for text scrolling
    prompt_additions:
      - "This is Pokemon Blue for Game Boy, a classic RPG where you catch and train Pokemon."
      - "Your main goal is to defeat all 8 gym leaders and become the champion."
      - "Use A to interact and confirm, B to cancel and run, and directional buttons to move."
      - "During battle sequences, select 'FIGHT' to use moves against opponent Pokemon."
      - "If text is still being typed on screen, do NOT press any buttons (use 'None' action)."
      - "In dialog screens, press A to advance text once it's fully displayed."

  zelda_links_awakening:
    rom: "/Users/ericflo/Development/emuvlm/roms/gb/Legend of Zelda, The - Link's Awakening (USA, Europe).zip"
    emulator: "pyboy"
    actions: ["Up", "Down", "Left", "Right", "A", "B", "Start", "Select"]
    action_delay: 0.4               # Seconds to wait after each action
    game_type: "zelda"              # Game type for specific handling
    # Game-specific timing configurations
    timing:
      menu_nav_delay: 0.3           # Delay for inventory navigation
      dialog_delay: 1.0             # Delay for NPC dialog
      screen_transition_delay: 0.7  # Delay for screen transitions
      item_use_delay: 0.5           # Delay after using items
    # Game-specific settings
    settings:
      detect_loading_screens: true  # Enable loading screen detection
      frame_analysis: true          # Enable more detailed frame analysis
      max_blank_frames: 5           # Maximum consecutive blank frames before skipping
    prompt_additions:
      - "This is The Legend of Zelda: Link's Awakening for Game Boy, an action-adventure game."
      - "Your goal is to collect musical instruments to awaken the Wind Fish and escape Koholint Island."
      - "Use A to use your sword or interact with objects, B to use your shield or cancel."
      - "Use Start to access your inventory and Select to view the map."
      - "You can assign items to the A and B buttons through the inventory menu."
      - "Talk to NPCs for guidance, explore dungeons, and solve puzzles to progress."

  final_fantasy_legend:
    rom: "/Users/ericflo/Development/emuvlm/roms/gb/Final Fantasy Legend, The (USA).zip"
    emulator: "pyboy"
    actions: ["Up", "Down", "Left", "Right", "A", "B", "Start", "Select"]
    action_delay: 0.5               # Seconds to wait after each action
    # Game-specific timing configurations
    timing:
      menu_nav_delay: 0.3           # Delay for menu navigation
      battle_command_delay: 0.4     # Delay between selecting battle commands
      battle_anim_delay: 1.0        # Delay for battle animations
      text_scroll_delay: 0.6        # Delay for text scrolling
    prompt_additions:
      - "This is Final Fantasy Legend for Game Boy, a turn-based RPG with tower climbing mechanics."
      - "Your goal is to climb the tower to paradise and meet the Creator."
      - "Use A to confirm selections and B to cancel or return to previous menus."
      - "In battle, select commands for each character in your party when prompted."
      - "Humans gain stats from items, Mutants gain abilities randomly, and Monsters transform by eating meat."
      - "The game uses a unique weapon durability system where weapons have limited uses."

  metroid_ii:
    rom: "/Users/ericflo/Development/emuvlm/roms/gb/Metroid II - Return of Samus (World).zip"
    emulator: "pyboy"
    actions: ["Up", "Down", "Left", "Right", "A", "B", "Start", "Select"]
    action_delay: 0.4               # Seconds to wait after each action
    # Game-specific timing configurations
    timing:
      screen_transition_delay: 0.7  # Delay for screen transitions
      weapon_switch_delay: 0.3      # Delay when switching weapons
    prompt_additions:
      - "This is Metroid II: Return of Samus for Game Boy, an action-adventure platform game."
      - "Your goal as Samus Aran is to exterminate all Metroid creatures on planet SR388."
      - "Use B to fire your weapon and A to jump. Hold down to crouch."
      - "Roll into a ball (morph ball) by pressing down twice, press A to place bombs."
      - "Earthquake effects signal the draining of lava, opening new areas to explore."
      - "Collect upgrades to access new areas and defeat stronger enemies."
      - "The status bar at the bottom shows energy, missiles, and remaining Metroids."

  kirby_dream_land:
    rom: "/Users/ericflo/Development/emuvlm/roms/gb/Kirby's Dream Land (USA, Europe).zip"
    emulator: "pyboy"
    actions: ["Up", "Down", "Left", "Right", "A", "B", "Start", "Select"]
    action_delay: 0.3               # Seconds to wait after each action
    # Game-specific timing configurations
    timing:
      ability_use_delay: 0.5        # Delay after using abilities
    prompt_additions:
      - "This is Kirby's Dream Land for Game Boy, a platformer where you control the pink puffball Kirby."
      - "Your goal is to recover food stolen by King Dedede and defeat him."
      - "Press B to inhale enemies and obstacles, then press B again to spit them out as projectiles."
      - "Press A to jump. Press A while floating to release air and descend."
      - "Press Up to float indefinitely after jumping or inhaling air."
      - "Unlike later Kirby games, you cannot copy enemy abilities in this first entry."
      - "Collect extra lives (represented by Kirby icons) to continue if you lose all your health."

  super_mario_land:
    rom: "/Users/ericflo/Development/emuvlm/roms/gb/Super Mario Land (World).zip"
    emulator: "pyboy"
    actions: ["Up", "Down", "Left", "Right", "A", "B", "Start", "Select"]
    action_delay: 0.3               # Seconds to wait after each action
    prompt_additions:
      - "This is Super Mario Land for Game Boy, a classic platformer starring Mario."
      - "Your goal is to rescue Princess Daisy from the alien Tatanga across 4 worlds."
      - "Press B to run and A to jump. Hold B while running to move faster."
      - "Jump on enemies to defeat them, or collect power-ups to shoot projectiles with B."
      - "The Super Mushroom makes Mario grow larger and can take one hit without losing a life."
      - "The Superball Flower lets Mario throw bouncing projectiles that can collect coins."
      - "There are also special vehicle stages where Mario pilots a submarine or airplane."

  tetris:
    rom: "/Users/ericflo/Development/emuvlm/roms/gb/Tetris (World).zip"
    emulator: "pyboy"
    actions: ["Up", "Down", "Left", "Right", "A", "B", "Start", "Select"]
    action_delay: 0.2               # Seconds to wait after each action
    prompt_additions:
      - "This is Tetris for Game Boy, the classic puzzle game of arranging falling blocks."
      - "Your goal is to complete horizontal lines of blocks, which will then disappear."
      - "Use Left/Right to move blocks horizontally, Down to accelerate their fall."
      - "Press A or B to rotate blocks clockwise."
      - "As you clear more lines, the blocks fall faster, increasing the difficulty."
      - "Try to plan your moves to set up for a Tetris (clearing 4 lines at once)."
      - "The game ends when the stack of blocks reaches the top of the playfield."

  castlevania_ii:
    rom: "/Users/ericflo/Development/emuvlm/roms/gb/Castlevania II - Belmont's Revenge (USA, Europe).zip"
    emulator: "pyboy"
    actions: ["Up", "Down", "Left", "Right", "A", "B", "Start", "Select"]
    action_delay: 0.4               # Seconds to wait after each action
    timing:
      weapon_use_delay: 0.5         # Delay after using weapons
    prompt_additions:
      - "This is Castlevania II: Belmont's Revenge for Game Boy, an action platformer."
      - "You play as Christopher Belmont, using your whip to defeat enemies and rescue your son."
      - "Press B to attack with your whip and A to jump."
      - "Press Up + B to use your equipped sub-weapon, which consumes hearts."
      - "Sub-weapons include the axe, holy water, cross (boomerang), and stopwatch."
      - "You can extend your whip's reach by collecting power-ups."
      - "Your goal is to clear the four castle stages and defeat Dracula."

  kid_icarus:
    rom: "/Users/ericflo/Development/emuvlm/roms/gb/Kid Icarus - Of Myths and Monsters (USA, Europe).zip"
    emulator: "pyboy"
    actions: ["Up", "Down", "Left", "Right", "A", "B", "Start", "Select"]
    action_delay: 0.3               # Seconds to wait after each action
    timing:
      weapon_use_delay: 0.3         # Delay after using weapons
    prompt_additions:
      - "This is Kid Icarus: Of Myths and Monsters for Game Boy, an action platformer."
      - "You play as Pit, an angel who must save Angel Land from the demon Orcos."
      - "Press B to shoot arrows and A to jump. Hold A to flap your wings and fly temporarily."
      - "You can only fly for a limited time before falling. The flight gauge is at the bottom."
      - "Enter doors to access shops, hot springs, and training rooms."
      - "Collect hearts from defeated enemies to purchase items in shops."
      - "Your goal is to retrieve the Three Sacred Treasures and defeat Orcos."

  mega_man_dr_wily:
    rom: "/Users/ericflo/Development/emuvlm/roms/gb/Mega Man - Dr. Wily's Revenge (USA).zip"
    emulator: "pyboy" 
    actions: ["Up", "Down", "Left", "Right", "A", "B", "Start", "Select"]
    action_delay: 0.3               # Seconds to wait after each action
    timing:
      weapon_switch_delay: 0.3      # Delay when switching weapons
    prompt_additions:
      - "This is Mega Man: Dr. Wily's Revenge for Game Boy, an action platformer."
      - "You play as Mega Man, fighting robots created by Dr. Wily."
      - "Press B to shoot and A to jump. Hold B to continuously fire."
      - "Press Start to access the weapon selection menu to switch weapons."
      - "Defeat Robot Masters to obtain their special weapons."
      - "Each Robot Master is weak to another's weapon. Finding these weaknesses is key."
      - "Energy tanks (E-Tanks) restore your health fully when used."

# Session configuration
sessions:
  enable_save: true                 # Enable session saving/loading
  save_dir: "output/sessions"       # Directory to store session data
  auto_save_interval: 50            # Auto-save session every X turns